language: csharp
solution: projects/GEDKeeper2.linux.sln

#after_success:
#  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"

install:
  - sudo apt-get install nunit-console
  - nuget restore ./projects/GEDKeeper2.linux.sln
 
script:
  - xbuild /p:Configuration=Debug /p:CIMode=true ./projects/GEDKeeper2.linux.sln
  - nunit-console ./projects/GKTests/bin/Debug/GKTests.dll
